/**
 * API Route handler for /api/habits/[id]/logs
 * Handles creating habit check-ins/completions
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { createHabitLogSchema } from '@/lib/validations';
import { ZodError } from 'zod';
import { Prisma } from '@prisma/client';

/**
 * POST /api/habits/[id]/logs
 * Creates a new habit log/check-in with automatic timestamp
 * 
 * @param request - Next.js request object with JSON body
 * @param params - Route parameters containing habit ID
 * @returns JSON response with created log (201) or error (404/409/500)
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: habitId } = await params;

    // Parse and validate request body
    const body = await request.json();
    const validatedData = createHabitLogSchema.parse(body);

    // Verify habit exists
    const habit = await prisma.habit.findUnique({
      where: { id: habitId },
    });

    if (!habit) {
      return NextResponse.json(
        { error: 'Habit not found' },
        { status: 404 }
      );
    }

    // Create habit log (completedAt is auto-generated by Prisma default)
    const log = await prisma.habitLog.create({
      data: {
        habitId,
        note: validatedData.note || null,
        // completedAt will be set to now() by Prisma @default(now())
      },
    });

    return NextResponse.json({ log }, { status: 201 });
  } catch (error) {
    // Handle Zod validation errors
    if (error instanceof ZodError) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: error.issues.map((issue) => ({
            field: issue.path.join('.'),
            message: issue.message,
          })),
        },
        { status: 400 }
      );
    }

    // Handle Prisma unique constraint violation (duplicate log)
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === 'P2002') {
        return NextResponse.json(
          {
            error: 'Log already exists',
            message: 'A check-in already exists for this habit at this time',
          },
          { status: 409 }
        );
      }
    }

    // Handle other errors
    console.error('Error creating habit log:', error);
    return NextResponse.json(
      { error: 'Failed to create habit log' },
      { status: 500 }
    );
  }
}
